name: Deploy HAMAS VPN

on:
  push:
    branches: ["main"]

permissions:
  contents: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Go binary
        run: |
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o awgusers main.go
      
      - name: Release push
        uses: softprops/action-gh-release@v2
        with:
          files: awgusers
          name: Amnezia HMS tools
          tag_name: HMS user adder